window.defaultNumber = '+1-888-546-5119';
window.defaultText = 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.';
window.text = {
    'xhamster.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'perfectgirls.net': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'gotporn.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'anysex.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'sex.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'bravotube.net': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'mylust.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'manporn.xxx': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'anybunny.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'txxx.com': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.',
    'findbestsolution.xyz': 'Your Apple ID was recently used at APPLE STORE for $299.99 Via Apple Pay Pre-Authorization!We have placed those request on hold to ensure safest and Security.Not you? Immediately call Apple Support +1-888-546-5119 to Freeze it!.'
};
